### ISSUE TITLE
HEALTHCHECK for the docker

### ISSUE THREAD

**Issue by draganm** [remote-tabs/remote-tabs#13]
It would be great if we could add `HEALTHCHECK` https://docs.docker.com/engine/reference/builder/#healthcheck for the service - would make rolling the deployment smoother

**Comment by zimbatm** [comment]
@nmattia do you want to add a dispatcher command to do the healthcheck or should I just add curl to the container?

**Comment by zimbatm** [comment]
^ I reverse-engineered how Dockerfiles are producing the healthcheck config in the above commit
